#!/usr/bin/with-contenv bash
APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}
APP_USER=aria2
APP_GROUP=aria2
APP_CONFIG=/etc/aria2

deluser "${APP_USER}" 2> /dev/null
delgroup "${APP_GROUP}" 2> /dev/null


if getent group ${APP_GID} > /dev/null; then
  delgroup `cut -d: -f1 < <(getent group ${APP_GID})` 2> /dev/null
fi

# add USER GID
if ! getent group ${APP_GROUP} > /dev/null; then
  addgroup -g ${APP_GID} ${APP_GROUP} > /dev/null 2>&1
fi

if ! getent group ${APP_GROUP}  > /dev/null; then
  APP_GROUP=`cut -d: -f1 < <(getent group ${APP_GID})`
fi

if getent passwd ${APP_UID} > /dev/null; then
  deluser `cut -d: -f1 < <(getent passwd ${APP_UID})` 2> /dev/null
fi


# create user with APP_UID
if ! getent passwd ${APP_USER} > /dev/null; then
  adduser -S -H \
    -s /bin/false \
    -u ${APP_UID} \
    -G ${APP_GROUP} \
     ${APP_USER} > /dev/null 2>&1
fi


CURR_SID=$(stat -c"%u:%g" ${APP_CONFIG})
if [ "$CURR_SID" != "$APP_UID:$APP_GID" ] ; then
  chown -R $APP_UID:$APP_GID ${APP_CONFIG}
fi


